#!/usr/bin/env bash
# =============================================================================
# cert_analyzer.sh — hermetic, offline cert-chain / expiry analyzer
# -----------------------------------------------------------------------------
# Purpose:      Sourceable library of PURE functions over a PEM certificate /
#               chain file. It answers the Let's Encrypt workstream's Phase-3
#               questions about a RESULTING certificate — is it valid now, how
#               many days remain, does its SAN cover the hostname, was it issued
#               by the EXPECTED CA, is renewal due — WITHOUT any network, any
#               ACME protocol, or any container boot. It validates a cert
#               regardless of HOW it was obtained (Caddy / lego / certbot /
#               Pebble / LE staging / LE prod), so it is client-AND-challenge-
#               AGNOSTIC and does NOT depend on the pending operator decisions
#               (design §9: DNS-01 vs HTTP-01, Caddy vs lego).
#
#               Every function is deterministic under an injected "now" epoch
#               (§11.4.50), so a single fixture can be tested as valid AND as
#               expired with NO time-travel. The analyzer is self-validated
#               against golden-good + golden-bad fixtures (§11.4.107(10)): a
#               golden-bad that the analyzer ACCEPTS is a bluff gate.
# Usage:        . tests/letsencrypt/cert_analyzer.sh   (source it; do not run)
#                 cert_not_expired    good_leaf.pem "$now_epoch"
#                 cert_days_remaining good_leaf.pem "$now_epoch"
#                 cert_san_matches    good_leaf.pem proxy.test
#                 cert_chain_roots_in leaf.pem       test_ca.pem
#                 cert_renewal_due    leaf.pem 30    "$now_epoch"
# Inputs:       PEM cert / chain files produced by openssl (public material
#               only — see §11.4.10 note below). All parsing is via
#               `openssl x509` / `openssl verify`; no network.
# Outputs:      Return code only (0 = the asserted property HOLDS, non-zero =
#               it does NOT hold or the input could not be parsed). The two
#               scalar accessors also print a value on stdout:
#                 cert_days_remaining -> signed integer days (may be negative)
# Side-effects: none (pure — reads the PEM file, never writes, never networks).
# Dependencies: POSIX sh, openssl (x509 + verify), GNU `date -d` (epoch parse),
#               awk/sed/tr.
# Cross-refs:   design docs/design/LETSENCRYPT_HTTPS.md §6 (unit row) +
#               LETSENCRYPT_HTTPS_PLAN.md Phase 3 (analyzer with golden-
#               good/golden-bad fixtures); Constitution §11.4.107(10) (self-
#               validated analyzer), §11.4.50 (deterministic now-seam),
#               §11.4.10 (no real secrets), §11.4.135 (regression guard).
# Shell:        POSIX-clean — parses under `sh -n` AND `bash -n` (§11.4.67).
#               No bash-only constructs ([[ ]], <<<, arrays, >( ), ${v^^}, local).
#
# DETERMINISTIC "now" SEAM (mirror the evidence.sh EVIDENCE_* override style;
# honour §11.4.50 — a single fixture is testable as valid AND expired):
#   Every time-aware function takes an OPTIONAL trailing <now_epoch> argument
#   (unix seconds, UTC). Precedence for "now", highest first:
#     (1) the explicit <now_epoch> positional argument (per-call);
#     (2) the CERT_ANALYZER_NOW_EPOCH env var (per-run seam);
#     (3) the real wall clock (`date -u +%s`) — production use.
#
# §11.4.10 NOTE — no real secrets. This library only ever READS certificate
# (public) material. The bundled fixtures are generated by
# tests/letsencrypt/fixtures/gen_fixtures.sh from EPHEMERAL throwaway test keys
# (self-signed test CAs — NOT real LE certs, NO production private keys). The
# generated *.key / *.csr / *.srl are gitignored (regenerated per §11.4.77);
# only the public *.pem certs are tracked.
# =============================================================================

# ----------------------------------------------------------------------------
# Internal helpers (prefix _cert_) — not part of the public contract.
# ----------------------------------------------------------------------------

# _cert_now [explicit_now_epoch]
# Resolve "now" (unix seconds) per the seam precedence documented above.
_cert_now() {
    if [ -n "${1:-}" ]; then
        printf '%s\n' "$1"
        return 0
    fi
    if [ -n "${CERT_ANALYZER_NOW_EPOCH:-}" ]; then
        printf '%s\n' "$CERT_ANALYZER_NOW_EPOCH"
        return 0
    fi
    date -u +%s
}

# _cert_epoch <pem> <start|end>
# Print the notBefore (start) or notAfter (end) of the FIRST (leaf) cert in the
# PEM as unix seconds. Non-zero return + no output on parse failure.
_cert_epoch() {
    _ce_pem=$1
    _ce_which=$2
    [ -f "$_ce_pem" ] || return 1
    if [ "$_ce_which" = "start" ]; then
        _ce_flag="-startdate"
    else
        _ce_flag="-enddate"
    fi
    # openssl prints e.g. "notAfter=Aug 30 00:00:00 2026 GMT"
    _ce_line=$(openssl x509 -in "$_ce_pem" -noout "$_ce_flag" 2>/dev/null) || return 1
    _ce_datestr=${_ce_line#*=}
    [ -n "$_ce_datestr" ] || return 1
    # GNU `date -d` parses the openssl date form directly.
    _ce_epoch=$(date -u -d "$_ce_datestr" +%s 2>/dev/null) || return 1
    [ -n "$_ce_epoch" ] || return 1
    printf '%s\n' "$_ce_epoch"
}

# ----------------------------------------------------------------------------
# Public analyzer contract.
# ----------------------------------------------------------------------------

# cert_not_expired <pem> [now_epoch]
# 0 iff NotBefore <= now < NotAfter (the cert is inside its validity window at
# "now"). An EXPIRED cert (now >= NotAfter) OR a NOT-YET-VALID cert
# (now < NotBefore) returns non-zero. A cert that cannot be parsed returns 2.
cert_not_expired() {
    _cne_pem=$1
    _cne_now=$(_cert_now "${2:-}")
    _cne_nb=$(_cert_epoch "$_cne_pem" start) || return 2
    _cne_na=$(_cert_epoch "$_cne_pem" end)   || return 2
    [ "$_cne_now" -ge "$_cne_nb" ] && [ "$_cne_now" -lt "$_cne_na" ]
}

# cert_days_remaining <pem> [now_epoch]
# Print the whole number of days from "now" to NotAfter (truncated toward zero;
# MAY be negative when the cert has already expired). Non-zero return (no
# output) on parse failure.
cert_days_remaining() {
    _cdr_pem=$1
    _cdr_now=$(_cert_now "${2:-}")
    _cdr_na=$(_cert_epoch "$_cdr_pem" end) || return 2
    _cdr_secs=$((_cdr_na - _cdr_now))
    printf '%d\n' $((_cdr_secs / 86400))
}

# cert_san_matches <pem> <hostname>
# 0 iff <hostname> is covered by the certificate's SAN dNSName set — as an
# EXACT token OR a single leading-wildcard (`*.example.com` covers exactly one
# extra left label, e.g. `a.example.com`, but NOT the bare `example.com` and
# NOT `a.b.example.com`). NEVER a naive substring match (mirrors the _code_in
# exact-token discipline in evidence.sh). Returns 2 on empty hostname / parse
# failure, 1 when no SAN entry matches.
cert_san_matches() {
    _csm_pem=$1
    _csm_host=$2
    [ -n "$_csm_host" ] || return 2
    [ -f "$_csm_pem" ] || return 2
    # Extract the dNSName tokens from the SAN extension, one per line.
    _csm_sans=$(openssl x509 -in "$_csm_pem" -noout -ext subjectAltName 2>/dev/null \
        | tr ',' '\n' \
        | sed -n 's/^[[:space:]]*DNS://Ip' \
        | tr -d '[:space:]')
    [ -n "$_csm_sans" ] || return 1
    for _csm_s in $_csm_sans; do
        # Exact match.
        if [ "$_csm_s" = "$_csm_host" ]; then
            return 0
        fi
        # Single leading-wildcard match: `*.suffix` covers one extra left label.
        case "$_csm_s" in
            \*.*)
                _csm_suffix=${_csm_s#\*}   # ".example.com"
                case "$_csm_host" in
                    *"$_csm_suffix")
                        _csm_label=${_csm_host%"$_csm_suffix"}   # left label(s)
                        case "$_csm_label" in
                            "" | *.*) : ;;          # empty or multi-label -> no match
                            *) return 0 ;;          # exactly one non-empty label -> match
                        esac
                        ;;
                esac
                ;;
        esac
    done
    return 1
}

# cert_chain_roots_in <leaf_pem> <expected_ca_pem>
# 0 iff <leaf_pem> verifies to <expected_ca_pem> — i.e. the leaf was ISSUED by
# the EXPECTED CA. This is how a test asserts "issued by the Pebble test CA" or
# "issued by LE staging/prod". A cert signed by a DIFFERENT / self CA returns
# non-zero. The check is ISSUANCE-only (validity-period-independent via
# -no_check_time) so it is orthogonal to cert_not_expired: an expired cert that
# roots correctly still PASSes the chain check (and FAILs the expiry check).
# Returns 2 when either file is missing.
cert_chain_roots_in() {
    _ccr_leaf=$1
    _ccr_ca=$2
    [ -f "$_ccr_leaf" ] && [ -f "$_ccr_ca" ] || return 2
    openssl verify -no_check_time -CAfile "$_ccr_ca" "$_ccr_leaf" >/dev/null 2>&1
}

# cert_renewal_due <pem> <threshold_days> [now_epoch]
# 0 (renewal DUE) iff cert_days_remaining <= <threshold_days> — the renewal
# trigger. An already-expired cert (negative days) is always due. Non-zero
# (NOT due) when more than <threshold_days> remain. Returns 2 on parse failure.
cert_renewal_due() {
    _crd_pem=$1
    _crd_thresh=$2
    _crd_days=$(cert_days_remaining "$_crd_pem" "${3:-}") || return 2
    [ "$_crd_days" -le "$_crd_thresh" ]
}
